  
  ### This script 1) standardizes all age entries in the openarch burgerlijke stand, 
  #               2) from the files generated by openarch_csv_per_certificatetype
  
  #Load required packages
  library("data.table"); library("tidyr"); library("dplyr")

  #Set working directory
  setwd("C:\\Surfdrive\\Data\\OpenArch\\")
  
  #Open data sets
 # Birth <- fread("openarch_birth.csv.gz")
 # Marriage <- fread("openarch_marriage.csv.gz")
  Death <- fread("C:\\Users\\Ruben\\Documents\\02. Werk\\Clariah\\openarch\\openarch_deaths_amco.csv.gz")
  
  #load functions
    clean_age <- function(db,AgeVar,NewVarName="cleaned"){
      df <- as.data.frame(table(AgeVar))
      df$Var1 <- as.character(df$AgeVar)
    #remove entries that are not ages
      df$Var1 <- ifelse(df$Var1=="-", "", df$Var1) #remove missings indicated with -
      df$Var1 <- ifelse(df$Var1=="9999", "",df$Var1) #remove missings indicated with 9999
      df$Var1 <- ifelse(is.na(as.numeric(gsub("\\D", "", df$Var1))), "", df$Var1) #remove string without digit
      df$Var1 <- ifelse(grepl("\\d-\\d{4}", df$Var1) | grepl("\\d \\d{4}", df$Var1),"", df$Var1) #remove dates
      df$Var1 <- ifelse(grepl("tussen", df$Var1), "",df$Var1) #remove entries with #
      df$Var1 <- ifelse(grepl("uur", df$Var1), "",df$Var1) #remove entries with #
    #remove redundant information
      df$Var1 <- gsub("oud ", "", df$Var1); df$Var1 <- gsub(" oud", "", df$Var1) #oud
      df$Var1 <- gsub("circa ", "", df$Var1) #remove leading circa
      df$Var1 <- gsub("ca ", "", df$Var1); df$Var1 <- gsub("ca\\. ", "", df$Var1); df$Var1 <- gsub("ca\\.", "", df$Var1); df$Var1 <- gsub("ca", "", df$Var1) #remove all variations ca's
      df$Var1 <- gsub("juist ", "", df$Var1) #remove juist
      df$Var1 <- gsub("om de ", "", df$Var1) #remove om de
      df$Var1 <- gsub("omstreeks ", "", df$Var1) #remove omstreeks
      df$Var1 <- gsub("omtrent ", "", df$Var1); df$Var1 <- gsub(" omtrent", "", df$Var1); df$Var1 <- gsub("omtrent", "", df$Var1) #remove all variations omtrent
      df$Var1 <- gsub("ongeveer ", "", df$Var1); df$Var1 <- gsub(" ongeveer", "", df$Var1); df$Var1 <- gsub("ong\\.", "", df$Var1) #remove all variations ongeveer
      df$Var1 <- gsub("thans ", "", df$Var1) #remove thans
      df$Var1 <- gsub("vermoedelijk ", "", df$Var1) #remove vermoedelijk
      df$Var1 <- ifelse(grepl("bijn", df$Var1) | grepl("bina", df$Var1) | grepl("nagenoeg", df$Var1),
                       substr(as.numeric(gsub("\\D", "", df$Var1)),1,2),df$Var1) #remove bijna & nagenoeg: 26, almost 27 -> 26
      df$Var1 <- ifelse(grepl("rui", df$Var1) | grepl("uim", df$Var1),
                       as.numeric(gsub("\\D", "", df$Var1)),df$Var1) #remove all variations of ruim
      df$Var1 <- ifelse(grepl("-", df$Var1),
                       as.numeric(gsub("\\D", "", df$Var1)),df$Var1) #remove - and trailing text
      df$Var1 <- ifelse(grepl("/", df$Var1),
                       as.numeric(gsub("\\D", "", substr(df$Var1,1,2))),df$Var1) #select age before 1/2 or trailing information
      df$Var1 <- ifelse(grepl("&", df$Var1), substr(df$Var1,1,2),df$Var1) #drop information on months
      df$Var1 <- ifelse(grepl(" en ", df$Var1), substr(df$Var1,1,2),df$Var1) #drop information on months
    #duplicated information on age
      df$Var1 <- ifelse(grepl(";", df$Var1),
                       substr(as.numeric(gsub("\\D", "", df$Var1)),1,2),df$Var1) #delete repeated number after ;
      df$Var1 <- ifelse(grepl("\\d{4}", df$Var1) & as.numeric(substr(gsub("\\D", "", df$Var1),1,2))==as.numeric(substr(gsub("\\D", "", df$Var1),3,4)), 
                       substr(gsub("\\D", "", df$Var1),1,2), df$Var1) #remove duplicated numbers
      df$Var1 <- ifelse(grepl("\\d{4}", df$Var1) & as.numeric(substr(gsub("\\D", "", df$Var1),1,2))+1==as.numeric(substr(gsub("\\D", "", df$Var1),3,4)), 
                       substr(gsub("\\D", "", df$Var1),1,2), df$Var1) #remove duplicated numbers with 1 year positive difference
      df$Var1 <- ifelse(grepl("\\d{4}", df$Var1) & as.numeric(substr(gsub("\\D", "", df$Var1),1,2))-1==as.numeric(substr(gsub("\\D", "", df$Var1),3,4)), 
                       substr(gsub("\\D", "", df$Var1),1,2), df$Var1) #remove duplicated numbers with 1 year negative difference
      df$Var1 <- ifelse(grepl("\\d{4}", df$Var1),"", df$Var1) #delete remaining duplicated numbers
      df$Var1 <- ifelse(grepl(" of ", df$Var1), 
                       substr(gsub("\\D", "", df$Var1),1,2), df$Var1) #remove duplicated numbers with 1 year positive difference
    #remove months
      df$Var1 <- ifelse(grepl("jan", df$Var1),"",df$Var1) #remove entries mentioning January
      df$Var1 <- ifelse(grepl("feb", df$Var1),"",df$Var1) #remove entries mentioning February
      df$Var1 <- ifelse(grepl("maart", df$Var1),"",df$Var1) #remove entries mentioning March
      df$Var1 <- ifelse(grepl("apr", df$Var1),"",df$Var1) #remove entries mentioning April
      df$Var1 <- ifelse(grepl("mei", df$Var1),"",df$Var1) #remove entries mentioning May
      df$Var1 <- ifelse(grepl("jun", df$Var1),"",df$Var1) #remove entries mentioning June
      df$Var1 <- ifelse(grepl("jul", df$Var1),"",df$Var1) #remove entries mentioning July
      df$Var1 <- ifelse(grepl("aug", df$Var1),"",df$Var1) #remove entries mentioning August
      df$Var1 <- ifelse(grepl("sep", df$Var1),"",df$Var1) #remove entries mentioning September
      df$Var1 <- ifelse(grepl("okt", df$Var1),"",df$Var1) #remove entries mentioning October
      df$Var1 <- ifelse(grepl("nov", df$Var1),"",df$Var1) #remove entries mentioning November
      df$Var1 <- ifelse(grepl("dec", df$Var1),"",df$Var1) #remove entries mentioning December
    #remove noice introduced by special characters.
      df$Var1 <- gsub("`", "", df$Var1) #remove ``
      df$Var1 <- gsub("\'", "", df$Var1) #remove '
      df$Var1 <- gsub("\\[", "", df$Var1) #remove [
      df$Var1 <- gsub("\\]", "", df$Var1) #remove ]
      df$Var1 <- gsub("\\\\", "", df$Var1) #remove \
      df$Var1 <- gsub("~","",df$Var1) #remove ~
      df$Var1 <- ifelse(grepl("\\(", df$Var1),
                       as.numeric(gsub("\\D", "", df$Var1)),df$Var1)
      df$Var1 <- ifelse(grepl("±", df$Var1),
                       as.numeric(gsub("\\D", "",df$Var1)),df$Var1)
    #remove unintelligible entries
      df$Var1 <- ifelse(grepl("\\?", df$Var1),"", df$Var1) #remove entries with ?
      df$Var1 <- ifelse(grepl("\\%", df$Var1),"", df$Var1) #remove entries with %
      df$Var1 <- ifelse(grepl("!", df$Var1),"", df$Var1) #remove entries with !
      df$Var1 <- ifelse(grepl(">", df$Var1), "",df$Var1) #remove entries with >
      df$Var1 <- ifelse(grepl("meer dan", df$Var1), "",df$Var1) #remove entries with >
      df$Var1 <- ifelse(grepl("<", df$Var1), "",df$Var1) #remove entries with <
      df$Var1 <- ifelse(grepl("#", df$Var1), "",df$Var1) #remove entries with #
      df$Var1 <- ifelse(grepl("@", df$Var1), "",df$Var1) #remove entries with @
      df$Var1 <- ifelse(grepl("\\+", df$Var1), "",df$Var1) #remove entries with +
    #maand of dag vermeld
      df$Var1 <- ifelse(grepl("mnd", df$Var1), 
                       substr(as.numeric(gsub("\\D", "", df$Var1)),1,2),df$Var1)
      df$Var1 <- ifelse(grepl("maa", df$Var1), 
                       substr(as.numeric(gsub("\\D", "", df$Var1)),1,2),df$Var1)
      df$Var1 <- ifelse(grepl("wk", df$Var1), 
                       substr(as.numeric(gsub("\\D", "", df$Var1)),1,2),df$Var1)
      df$Var1 <- ifelse(grepl("dag", df$Var1), 
                       substr(as.numeric(gsub("\\D", "", df$Var1)),1,2),df$Var1)
      df$Var1 <- ifelse(grepl("dg", df$Var1), 
                       substr(as.numeric(gsub("\\D", "", df$Var1)),1,2),df$Var1)
    #delete variations on jaar
      df$Var1 <- ifelse(grepl("j", df$Var1),
                       as.numeric(gsub("\\D", "", df$Var1)),df$Var1)
      df$Var1 <- ifelse(grepl("aar", df$Var1),
                       as.numeric(gsub("\\D", "", df$Var1)),df$Var1)
    #check other text
      df$Var1 <- ifelse(grepl("no",df$Var1),"", df$Var1)
      df$Var1 <- ifelse(grepl("\\D", df$Var1),
                       as.numeric(gsub("\\D", "", df$Var1)),df$Var1)
    #clean remaining entries
      df$Var1 <- ifelse(df$Var1=="0" | df$Var1=="00" | df$Var1=="000", "", df$Var1) #delete 0-entries
      df$Var1 <- ifelse(substr(df$Var1,1,1)=="0", substr(df$Var1,2,nchar(df$Var1)), df$Var1) #delete leading 0's
      df$Var1 <- ifelse(substr(df$Var1,1,2)==substr(df$Var1,3,4), substr(df$Var1,1,2), df$Var1) #repair duplicated numbers
      df$Var1 <- ifelse(df$Var1=="", df$Var1,
                       ifelse(as.numeric(df$Var1)>100 | as.numeric(df$Var1)<13, "", df$Var1))
      if(NewVarName=="cleaned"){
        colnames(df)[3] <- paste0(gsub(paste0(deparse(substitute(db)),"\\$"), "", deparse(substitute(AgeVar))),"_cleaned")
        df <- df[,c("AgeVar", paste0(gsub(paste0(deparse(substitute(db)),"\\$"), "", deparse(substitute(AgeVar))),"_cleaned"))]
      }
      else{
        colnames(df)[3] <- NewVarName
        df <- df[,c("AgeVar", NewVarName)]
      }
      df <- merge(db, df, by.x=gsub(paste0(deparse(substitute(db)),"\\$")  , "", deparse(substitute(AgeVar))), by.y="AgeVar")
      df
      }
  
  #load functions
    clean_age_death <- function(db,AgeVar,NewVarName="cleaned"){
      df <- as.data.frame(table(AgeVar))
      df$Var1 <- as.character(df$AgeVar)
    #make fields:
      df$cleaned <- tolower(df$Var1)
      df$year <- NA
      df$month <- NA
      df$week <- NA
      df$day <- NA
    #fix import errors
      df$cleaned <- gsub("ã,â¡ã,â½ã,â¡", " en een half", df$cleaned)
      df$cleaned <- gsub("ã,â¡½ã,â¡", "en een half", df$cleaned)
      df$cleaned <- gsub("ãfâ", "en", df$cleaned)
      df$cleaned <- gsub("ã«", "e", df$cleaned)
      df$cleaned <- gsub("ã©", "e", df$cleaned)
      df$cleaned <- gsub("ãf", "a", df$cleaned)
      df$cleaned <- gsub("ã,â½", " en 1 half", df$cleaned); df$cleaned <- gsub("â½", " en 1 half", df$cleaned)
      df$cleaned <- gsub("ã,â¼", " en 1 kwart", df$cleaned); df$cleaned <- gsub("â¼", " en 1 kwart", df$cleaned)
      df$cleaned <- gsub("ã,â¾", " en 3 kwart", df$cleaned); df$cleaned <- gsub("â¾", " en 3 kwart", df$cleaned)
      df$cleaned <- gsub("ã,â¡", "", df$cleaned)
      df$cleaned <- gsub("ã,â±", "", df$cleaned); df$cleaned <- gsub("â±", "", df$cleaned)
      df$cleaned <- gsub("ã,â¢", "", df$cleaned)
      df$cleaned <- gsub("ã,â«", "", df$cleaned)
      df$cleaned <- gsub("ã,â«", "", df$cleaned)
      df$cleaned <- gsub("ãfâ", "a", df$cleaned)
      df$cleaned <- gsub("ãf", "a", df$cleaned)
      df$cleaned <- gsub("ã¡", "a", df$cleaned)
      df$cleaned <- gsub("ã,", "", df$cleaned)
      df$cleaned <- gsub("ã,â¡", "", df$cleaned)
    #missing characters
      df$cleaned <- ifelse(grepl("\\?", df$cleaned), "", df$cleaned)
      df$cleaned <- ifelse(grepl("\\!", df$cleaned), "", df$cleaned)
      df$cleaned <- ifelse(grepl("%", df$cleaned), "", df$cleaned)
      df$cleaned <- ifelse(grepl("&", df$cleaned), "", df$cleaned)
      df$cleaned <- ifelse(grepl("\\*", df$cleaned), "", df$cleaned)
      df$cleaned <- ifelse(grepl("\\$", df$cleaned), "", df$cleaned)
      df$cleaned <- ifelse(grepl("\\.\\.", df$cleaned) & grepl("\\d", substr(df$cleaned,1,2))==F, "", df$cleaned)
      df$cleaned <- ifelse(substr(df$cleaned,1,1)=="<", "", df$cleaned)
      df$cleaned <- gsub("<.*", "", df$cleaned)
      df$cleaned <- ifelse(grepl("meer dan", df$cleaned), "", df$cleaned)
    #fix fractions
      df$cleaned <- gsub("1/4", " en 1 kwart", df$cleaned) #1/4
      df$cleaned <- gsub("3/4", " en 3 kwart", df$cleaned) #3/4
      df$cleaned <- gsub("5/4", "5 kwart", df$cleaned) #5/4
      df$cleaned <- gsub("7/4", "7 kwart", df$cleaned) #7/4
      df$cleaned <- gsub("-1/2", ".5", df$cleaned) #1/2
      df$cleaned <- gsub(" - 1/2", ".5", df$cleaned) #1/2
      df$cleaned <- gsub("1/2", ".5", df$cleaned) #1/2
      df$cleaned <- gsub("/1-2", ".5", df$cleaned) #1/2
      df$cleaned <- gsub("1\\.2", ".5", df$cleaned) #1/2
      df$cleaned <- gsub("1/3", "1 derde", df$cleaned) #1/3
      df$cleaned <- gsub("2/3", "2 derde", df$cleaned) #2/3
      df$cleaned <- gsub("1/5", "4 maanden", df$cleaned) #1/5
      df$cleaned <- gsub("1/6", "2 maanden", df$cleaned) #1/6
    #comma's with dots
      df$cleaned <- gsub(",25", "en 1 kwart", df$cleaned)
      df$cleaned <- gsub(",5", ".5", df$cleaned)
      df$cleaned <- gsub(",75", "en 3 kwart", df$cleaned)
    #remove missings
      df$cleaned <- ifelse(df$cleaned=="-", "", df$cleaned) #remove missings indicated with -
      df$cleaned <- ifelse(substr(df$cleaned,1,5)=="niet ", "",df$cleaned) #remove niet opgenomen [not entered]
      df$cleaned <- ifelse(grepl("onbekend", df$cleaned), "", df$cleaned) #remove onbekend [unknown]
      df$cleaned <- ifelse(grepl("999", df$cleaned), "", df$cleaned) #remove missings indicated with 999
      df$cleaned <- ifelse(grepl("--", df$cleaned), "", df$cleaned) #remove missings indicated with 999
    #remove guestimates
      df$cleaned <- ifelse(grepl("schat", df$cleaned), "", df$cleaned) #remove schatting [estimation]
      df$cleaned <- ifelse(grepl("gis", df$cleaned), "", df$cleaned) #remove gissing [conjecture]
      df$cleaned <- ifelse(grepl("presumtie", df$cleaned), "", df$cleaned) #remove presumptief [assumption]
    #no age information
      df$cleaned <- ifelse(substr(df$cleaned,1,3)=="geb", "", df$cleaned)
    #remove odd fraction entries
      df$cleaned <- ifelse(grepl("\\d:\\d", df$cleaned), "", df$cleaned) #entries starting with 0: ...
      df$cleaned <- ifelse(grepl("\\d:ã", df$cleaned), "", df$cleaned) #entries starting with 0:ã ...
    #recode stillborn children
      df$day <- ifelse(grepl("levenl", df$cleaned), "1", df$day) #stillborn
      df$cleaned <- ifelse(grepl("levenl", df$cleaned), "1",df$cleaned) #stillborn
      df$cleaned <- ifelse(grepl("dood", df$cleaned) & grepl("geb", df$cleaned), "1",df$cleaned) #stillborn
    #recode short-lived children
      df$day <- ifelse(grepl("levend", df$cleaned), "1", df$day) #short-lived children
      df$cleaned <- ifelse(grepl("levend", df$cleaned), "",df$cleaned) #short-lived children
      df$day <- ifelse(grepl("ogenblik", df$cleaned), "1", df$day) #short-lived children
      df$cleaned <- ifelse(grepl("ogenblik", df$cleaned), "",df$cleaned) #short-lived children
      df$day <- ifelse(grepl("moment", df$cleaned), "1", df$day) #short-lived children
      df$cleaned <- ifelse(grepl("moment", df$cleaned), "",df$cleaned) #short-lived children
      df$day <- ifelse(grepl("dadelijk", df$cleaned), "1", df$day) #short-lived children
      df$cleaned <- ifelse(grepl("dadelijk", df$cleaned), "",df$cleaned) #short-lived children
      df$day <- ifelse(grepl("nog geen", df$cleaned), "1", df$day) #short-lived children
      df$cleaned <- ifelse(grepl("nog geen", df$cleaned), "",df$cleaned) #short-lived children
      df$day <- ifelse(grepl("geleefd", df$cleaned), "1", df$day) #short-lived children
      df$cleaned <- ifelse(grepl("geleefd", df$cleaned), "",df$cleaned) #short-lived children
      df$day <- ifelse(grepl("enige", df$cleaned), "1", df$day) #short-lived children
      df$cleaned <- ifelse(grepl("enige", df$cleaned), "",df$cleaned) #short-lived children
      df$day <- ifelse(grepl("meteen", df$cleaned), "1", df$day) #short-lived children
      df$cleaned <- ifelse(grepl("meteen", df$cleaned), "",df$cleaned) #short-lived children
      df$day <- ifelse(grepl("kort", df$cleaned), "1", df$day) #short-lived children
      df$cleaned <- ifelse(grepl("kort", df$cleaned), "",df$cleaned) #short-lived children
    #remove twins
      df$cleaned <- gsub("een van een tweeling", "", df$cleaned) #twin
      df$cleaned <- gsub("tweeling", "", df$cleaned) #twin
    #remove ranges
      #tussen [between]
      df$month <- ifelse(grepl("tussen", df$cleaned) & grepl("maand", df$cleaned), gsub("\\D", "", sub(" en .*", '', df$cleaned)), df$month)
      df$cleaned <- ifelse(grepl("tussen", df$cleaned) & grepl("maand", df$cleaned), "", df$cleaned)
      df$year <- ifelse(grepl("tussen", df$cleaned) & as.numeric(gsub("\\D", "", sub(".* en ", '', df$cleaned)))-as.numeric(gsub("\\D", "", sub(" en .*", '', df$cleaned)))==2, 
                        (as.numeric(gsub("\\D", "", sub(".* en ", '', df$cleaned)))+as.numeric(gsub("\\D", "", sub(" en .*", '', df$cleaned))))/2, df$year)
      df$year <- ifelse(grepl("tussen", df$cleaned) & as.numeric(gsub("\\D", "", sub(".* en ", '', df$cleaned)))-as.numeric(gsub("\\D", "", sub(" en .*", '', df$cleaned)))==1, 
                        gsub("\\D", "", sub(" en .*", '', df$cleaned)), df$year)
      df$cleaned <- ifelse(grepl("tussen", df$cleaned), "", df$cleaned) #remove entries with age range 
      #tot [until]
      df$month <- ifelse(grepl("tot", df$cleaned) & grepl("maand", df$cleaned), gsub("\\D", "", sub("tot.*", '', df$cleaned)), df$month)
      df$cleaned <- ifelse(grepl("tot", df$cleaned) & grepl("maand", df$cleaned), "", df$cleaned)
      df$year <- ifelse(grepl("tot", df$cleaned) & as.numeric(gsub("\\D", "", sub(".*tot", '', df$cleaned)))-as.numeric(gsub("\\D", "", sub("tot.*", '', df$cleaned)))==2, 
                        (as.numeric(gsub("\\D", "", sub(".*tot", '', df$cleaned)))+as.numeric(gsub("\\D", "", sub("tot.*", '', df$cleaned))))/2, df$year)
      df$year <- ifelse(grepl("tot", df$cleaned) & as.numeric(gsub("\\D", "", sub(".*tot", '', df$cleaned)))-as.numeric(gsub("\\D", "", sub("tot.*", '', df$cleaned)))==1, 
                        gsub("\\D", "", sub("tot.*", '', df$cleaned)), df$year)
      df$cleaned <- ifelse(grepl("tot", df$cleaned), "", df$cleaned) #remove entries with age range
      # a [approximately]
      df$cleaned <- gsub("bijn a", "bijna", df$cleaned)
      df$day <- ifelse(grepl(" a ", df$cleaned) & grepl("uren", df$cleaned), 1, df$day)
      df$cleaned <- ifelse(grepl(" a ", df$cleaned) & grepl("uren", df$cleaned), "", df$cleaned)
      df$day <- ifelse(grepl(" a ", df$cleaned) & grepl("g", df$cleaned), gsub("\\D", "", sub(" a .*", '', df$cleaned)), df$day)
      df$cleaned <- ifelse(grepl(" a ", df$cleaned) & grepl("g", df$cleaned), "", df$cleaned)
      df$week <- ifelse(grepl(" a ", df$cleaned) & grepl("w", df$cleaned), gsub("\\D", "", sub(" a .*", '', df$cleaned)), df$week)
      df$cleaned <- ifelse(grepl(" a ", df$cleaned) & grepl("w", df$cleaned), "", df$cleaned)
      df$month <- ifelse(grepl(" a ", df$cleaned) & grepl("maand", df$cleaned), gsub("\\D", "", sub(" a .*", '', df$cleaned)), df$month)
      df$cleaned <- ifelse(grepl(" a ", df$cleaned) & grepl("maand", df$cleaned), "", df$cleaned)
      df$year <- ifelse(grepl(" a ", df$cleaned) & as.numeric(gsub("\\D", "", sub(".* a ", '', df$cleaned)))-as.numeric(gsub("\\D", "", sub(" a .*", '', df$cleaned)))==2, 
                        (as.numeric(gsub("\\D", "", sub(".* a ", '', df$cleaned)))+as.numeric(gsub("\\D", "", sub(" a .*", '', df$cleaned))))/2, df$year)
      df$year <- ifelse(grepl(" a ", df$cleaned) & as.numeric(gsub("\\D", "", sub(".* a ", '', df$cleaned)))-as.numeric(gsub("\\D", "", sub(" a .*", '', df$cleaned)))==1, 
                        gsub("\\D", "", sub(" a .*", '', df$cleaned)), df$year)
      df$cleaned <- ifelse(grepl(" a ", df$cleaned), "", df$cleaned) #remove entries with age range
      #
      df$cleaned <- ifelse(grepl("\\d-\\d", df$cleaned), "", df$cleaned) #remove entries with age range
    #remove dates
      df$cleaned <- ifelse(grepl("\\d-\\d{4}", df$cleaned) & grepl("aar", df$cleaned) | 
                             grepl("\\d \\d{4}", df$cleaned) & grepl("aar", df$cleaned),substr(df$cleaned,1,2), df$cleaned) #extract age in years
      df$cleaned <- ifelse(grepl("\\d-\\d{4}", df$cleaned) & grepl("dag", df$cleaned) | 
                             grepl("\\d \\d{4}", df$cleaned) & grepl("dag", df$cleaned),substr(df$cleaned,1,2), df$cleaned) #extract age in days
      df$cleaned <- ifelse(grepl("\\d-\\d{4}", df$cleaned) | grepl("\\d \\d{4}", df$cleaned),"", df$cleaned) #remove dates
    #recode hours / minutes
      #minutes
      df$day <- ifelse(grepl("min", df$cleaned) & grepl("min ", df$cleaned)==F & grepl("minus", df$cleaned)==F, "1", df$day)
      df$cleaned <- ifelse(grepl("min", df$cleaned) & grepl("min ", df$cleaned)==F & grepl("minus", df$cleaned)==F, "",df$cleaned)
      #1/4 hour
      df$day <- ifelse(grepl("kwartier", df$cleaned), "1", df$day)
      df$cleaned <- ifelse(grepl("kwartier", df$cleaned), "",df$cleaned)
      df$day <- ifelse(grepl("kwart", df$cleaned) & grepl("uur", df$cleaned), "1", df$day)
      df$cleaned <- ifelse(grepl("kwart", df$cleaned) & grepl("uur", df$cleaned), "",df$cleaned)
      #hours
      df$day <- ifelse(grepl("uur", df$cleaned) & substr(df$cleaned,1,1)=="0", 1, df$day)
      df$cleaned <- ifelse(grepl("uur", df$cleaned) & substr(df$cleaned,1,1)=="0", "", df$cleaned)
      #
      df$day <- ifelse(grepl("u\\(u", df$cleaned), 1, df$day)
      df$cleaned <- ifelse(grepl("u\\(u", df$cleaned), "", df$cleaned)
      #
      df$year <- ifelse(grepl("uur", df$cleaned) & grepl("ja", df$cleaned), gsub(" ", "",substr(df$cleaned,1,2)), df$year); df$year <- ifelse(grepl("uren", df$cleaned) & grepl("ja", df$cleaned), gsub(" ", "",substr(df$cleaned,1,2)), df$year)
      df$month <- ifelse(grepl("uur", df$cleaned) & grepl("ja", df$cleaned), gsub(" ", "",substr(df$cleaned,8,9)), df$month); df$month <- ifelse(grepl("uren", df$cleaned) & grepl("ja", df$cleaned), gsub(" ", "",substr(df$cleaned,8,9)), df$month)
      df$cleaned <- ifelse(grepl("uur", df$cleaned) & grepl("ja", df$cleaned), "", df$cleaned); df$cleaned <- ifelse(grepl("uren", df$cleaned) & grepl("ja", df$cleaned), "", df$cleaned)
      #
      df$month <- ifelse(grepl("uur", df$cleaned) & grepl("ma", df$cleaned), gsub(" ", "",substr(df$cleaned,1,2)), df$month); df$month <- ifelse(grepl("uren", df$cleaned) & grepl("ma", df$cleaned), gsub(" ", "",substr(df$cleaned,1,2)), df$month)
      df$cleaned <- ifelse(grepl("uur", df$cleaned) & grepl("ma", df$cleaned), "", df$cleaned); df$cleaned <- ifelse(grepl("uren", df$cleaned) & grepl("ma", df$cleaned), "", df$cleaned)
      #
      df$day <- ifelse(grepl("uur", df$cleaned) & grepl("da", df$cleaned), as.numeric(gsub("\\D", "", substr(df$cleaned,1,2))), df$day); df$day <- ifelse(grepl("uren", df$cleaned) & grepl("da", df$cleaned), as.numeric(gsub("\\D", "", substr(df$cleaned,1,2))), df$day)
      df$cleaned <- ifelse(grepl("uur", df$cleaned) & grepl("da", df$cleaned), "", df$cleaned); df$cleaned <- ifelse(grepl("uren", df$cleaned) & grepl("da", df$cleaned), "", df$cleaned)
      #
      df$day <- ifelse(grepl("uur", df$cleaned) & nchar(gsub("\\D", "", substr(df$cleaned,1,2)))==2 , floor(as.numeric(gsub("\\D", "", substr(df$cleaned,1,2))) / 24), df$day)
      df$day <- ifelse(grepl("uren", df$cleaned) & nchar(gsub("\\D", "", substr(df$cleaned,1,2)))==2 , floor(as.numeric(gsub("\\D", "", substr(df$cleaned,1,2))) / 24), df$day); df$day[df$day=="0"] <- 1
      df$cleaned <- ifelse(grepl("uur", df$cleaned) & nchar(gsub("\\D", "", substr(df$cleaned,1,2)))==2 , "", df$cleaned); df$cleaned <- ifelse(grepl("uren", df$cleaned) & nchar(gsub("\\D", "", substr(df$cleaned,1,2)))==2 , "", df$cleaned)
      #
      df$day <- ifelse(grepl("uur", df$cleaned), 1, df$day); df$day <- ifelse(grepl("ure", df$cleaned), 1, df$day)
      df$cleaned <- ifelse(grepl("uur", df$cleaned), "", df$cleaned); df$cleaned <- ifelse(grepl("ure", df$cleaned), "", df$cleaned)
    #recode etmaal [24 hours]
      df$day <- ifelse(grepl("etmaal", df$cleaned), 1, df$day)
      df$cleaned <- ifelse(grepl("etmaal", df$cleaned), "", df$cleaned)
    #fix numbers
      #100
      df$cleaned <- gsub("honderd", "100", df$cleaned) #100
      #90
      df$cleaned <- gsub("negen en negentig", "99", df$cleaned); df$cleaned <- gsub("negenennegentig", "99", df$cleaned) #99
      df$cleaned <- gsub("acht en negentig", "98", df$cleaned); df$cleaned <- gsub("achtennegentig", "98", df$cleaned) #98
      df$cleaned <- gsub("zeven en negentig", "97", df$cleaned); df$cleaned <- gsub("zevenennegentig", "97", df$cleaned) #97
      df$cleaned <- gsub("zes en negentig", "96", df$cleaned); df$cleaned <- gsub("zesennegentig", "96", df$cleaned) #96
      df$cleaned <- gsub("vijf en negentig", "95", df$cleaned); df$cleaned <- gsub("vijfennegentig", "95", df$cleaned) #95
      df$cleaned <- gsub("vier en negentig", "94", df$cleaned); df$cleaned <- gsub("vierennegentig", "94", df$cleaned) #94
      df$cleaned <- gsub("drie en negentig", "93", df$cleaned); df$cleaned <- gsub("drieennegentig", "93", df$cleaned) #93
      df$cleaned <- gsub("twee en negentig", "92", df$cleaned); df$cleaned <- gsub("tweeennegentig", "92", df$cleaned) #92
      df$cleaned <- gsub("een en negentig", "91", df$cleaned); df$cleaned <- gsub("eenennegentig", "91", df$cleaned) #91
      df$cleaned <- gsub("negentig", "90", df$cleaned) #90
      #80
      df$cleaned <- gsub("negen en tachtig", "89", df$cleaned); df$cleaned <- gsub("negenentachtig", "89", df$cleaned) #89
      df$cleaned <- gsub("acht en tachtig", "88", df$cleaned); df$cleaned <- gsub("achtentachtig", "88", df$cleaned) #88
      df$cleaned <- gsub("zeven en tachtig", "87", df$cleaned); df$cleaned <- gsub("zevenentachtig", "87", df$cleaned) #87
      df$cleaned <- gsub("zes en tachtig", "86", df$cleaned); df$cleaned <- gsub("zesentachtig", "86", df$cleaned) #86
      df$cleaned <- gsub("vijf en tachtig", "85", df$cleaned); df$cleaned <- gsub("vijfentachtig", "85", df$cleaned) #85
      df$cleaned <- gsub("vier en tachtig", "84", df$cleaned); df$cleaned <- gsub("vierentachtig", "84", df$cleaned) #84
      df$cleaned <- gsub("drie en tachtig", "83", df$cleaned); df$cleaned <- gsub("drieentachtig", "83", df$cleaned) #83
      df$cleaned <- gsub("twee en tachtig", "82", df$cleaned); df$cleaned <- gsub("tweeentachtig", "82", df$cleaned) #82
      df$cleaned <- gsub("een en tachtig", "81", df$cleaned); df$cleaned <- gsub("eenentachtig", "81", df$cleaned) #81
      df$cleaned <- gsub("tachtig", "80", df$cleaned) #80
      #70
      df$cleaned <- gsub("negen en zeventig", "79", df$cleaned); df$cleaned <- gsub("negenenzeventig", "79", df$cleaned) #79
      df$cleaned <- gsub("acht en zeventig", "78", df$cleaned); df$cleaned <- gsub("achtenzeventig", "78", df$cleaned) #78
      df$cleaned <- gsub("zeven en zeventig", "77", df$cleaned); df$cleaned <- gsub("zevenenzeventig", "77", df$cleaned) #77
      df$cleaned <- gsub("zes en zeventig", "76", df$cleaned); df$cleaned <- gsub("zesenzeventig", "76", df$cleaned) #76
      df$cleaned <- gsub("vijf en zeventig", "75", df$cleaned); df$cleaned <- gsub("vijfenzeventig", "75", df$cleaned) #75
      df$cleaned <- gsub("vier en zeventig", "74", df$cleaned); df$cleaned <- gsub("vierenzeventig", "74", df$cleaned) #74
      df$cleaned <- gsub("drie en zeventig", "73", df$cleaned); df$cleaned <- gsub("drieenzeventig", "73", df$cleaned) #73
      df$cleaned <- gsub("twee en zeventig", "72", df$cleaned); df$cleaned <- gsub("tweeenzeventig", "72", df$cleaned) #72
      df$cleaned <- gsub("een en zeventig", "71", df$cleaned); df$cleaned <- gsub("eenenzeventig", "71", df$cleaned) #71
      df$cleaned <- gsub("zeventig", "70", df$cleaned) #70
      #60
      df$cleaned <- gsub("negen en zestig", "69", df$cleaned); df$cleaned <- gsub("negenenzestig", "69", df$cleaned) #69
      df$cleaned <- gsub("acht en zestig", "68", df$cleaned); df$cleaned <- gsub("achtenzestig", "68", df$cleaned) #68
      df$cleaned <- gsub("zeven en zestig", "67", df$cleaned); df$cleaned <- gsub("zevenenzestig", "67", df$cleaned) #67
      df$cleaned <- gsub("zes en zestig", "66", df$cleaned); df$cleaned <- gsub("zesenzestig", "66", df$cleaned) #66
      df$cleaned <- gsub("vijf en zestig", "65", df$cleaned); df$cleaned <- gsub("vijfenzestig", "65", df$cleaned) #65
      df$cleaned <- gsub("vier en zestig", "64", df$cleaned); df$cleaned <- gsub("vierenzestig", "64", df$cleaned) #64
      df$cleaned <- gsub("drie en zestig", "63", df$cleaned); df$cleaned <- gsub("drieenzestig", "63", df$cleaned) #63
      df$cleaned <- gsub("twee en zestig", "62", df$cleaned); df$cleaned <- gsub("tweeenzestig", "62", df$cleaned) #62
      df$cleaned <- gsub("een en zestig", "61", df$cleaned); df$cleaned <- gsub("eenenzestig", "61", df$cleaned) #61
      df$cleaned <- gsub("zestig", "60", df$cleaned) #60
      #50
      df$cleaned <- gsub("negen en vijftig", "59", df$cleaned); df$cleaned <- gsub("negenenvijftig", "59", df$cleaned) #59
      df$cleaned <- gsub("acht en vijftig", "58", df$cleaned); df$cleaned <- gsub("achtenvijftig", "58", df$cleaned) #58
      df$cleaned <- gsub("zeven en vijftig", "57", df$cleaned); df$cleaned <- gsub("zevenenvijftig", "57", df$cleaned) #57
      df$cleaned <- gsub("zes en vijftig", "56", df$cleaned); df$cleaned <- gsub("zesenvijftig", "56", df$cleaned) #56
      df$cleaned <- gsub("vijf en vijftig", "55", df$cleaned); df$cleaned <- gsub("vijfenvijftig", "55", df$cleaned) #55
      df$cleaned <- gsub("vier en vijftig", "54", df$cleaned); df$cleaned <- gsub("vierenvijftig", "54", df$cleaned) #54
      df$cleaned <- gsub("drie en vijftig", "53", df$cleaned); df$cleaned <- gsub("drieenvijftig", "53", df$cleaned) #53
      df$cleaned <- gsub("twee en vijftig", "52", df$cleaned); df$cleaned <- gsub("tweeenvijftig", "52", df$cleaned) #52
      df$cleaned <- gsub("een en vijftig", "51", df$cleaned); df$cleaned <- gsub("eenenvijftig", "51", df$cleaned) #51
      df$cleaned <- gsub("vijftig", "50", df$cleaned) #50
      #40
      df$cleaned <- gsub("negen en veertig", "49", df$cleaned); df$cleaned <- gsub("negenenveertig", "49", df$cleaned) #49
      df$cleaned <- gsub("acht en veertig", "48", df$cleaned); df$cleaned <- gsub("achtenveertig", "48", df$cleaned) #48
      df$cleaned <- gsub("zeven en veertig", "47", df$cleaned); df$cleaned <- gsub("zevenenveertig", "47", df$cleaned) #47
      df$cleaned <- gsub("zes en veertig", "46", df$cleaned); df$cleaned <- gsub("zesenveertig", "46", df$cleaned) #46
      df$cleaned <- gsub("vijf en veertig", "45", df$cleaned); df$cleaned <- gsub("vijfenveertig", "45", df$cleaned) #45
      df$cleaned <- gsub("vier en veertig", "44", df$cleaned); df$cleaned <- gsub("vierenveertig", "44", df$cleaned) #44
      df$cleaned <- gsub("drie en veertig", "43", df$cleaned); df$cleaned <- gsub("drieenveertig", "43", df$cleaned) #43
      df$cleaned <- gsub("twee en veertig", "42", df$cleaned); df$cleaned <- gsub("tweeenveertig", "42", df$cleaned) #42
      df$cleaned <- gsub("een en veertig", "41", df$cleaned); df$cleaned <- gsub("eenenveertig", "41", df$cleaned) #41
      df$cleaned <- gsub("veertig", "40", df$cleaned) #40
      #30
      df$cleaned <- gsub("negen en dertig", "39", df$cleaned); df$cleaned <- gsub("negenendertig", "39", df$cleaned) #39
      df$cleaned <- gsub("acht en dertig", "38", df$cleaned); df$cleaned <- gsub("achtendertig", "38", df$cleaned) #38
      df$cleaned <- gsub("zeven en dertig", "37", df$cleaned); df$cleaned <- gsub("zevenendertig", "37", df$cleaned) #37
      df$cleaned <- gsub("zes en dertig", "36", df$cleaned); df$cleaned <- gsub("zesendertig", "36", df$cleaned) #36
      df$cleaned <- gsub("vijf en dertig", "35", df$cleaned); df$cleaned <- gsub("vijfendertig", "35", df$cleaned) #35
      df$cleaned <- gsub("vier en dertig", "34", df$cleaned); df$cleaned <- gsub("vierendertig", "34", df$cleaned) #34
      df$cleaned <- gsub("drie en dertig", "33", df$cleaned); df$cleaned <- gsub("drieendertig", "33", df$cleaned) #33
      df$cleaned <- gsub("twee en dertig", "32", df$cleaned); df$cleaned <- gsub("tweeendertig", "32", df$cleaned); df$cleaned <- gsub("tweenderti", "32", df$cleaned) #32
      df$cleaned <- gsub("een en dertig", "31", df$cleaned); df$cleaned <- gsub("eenendertig", "31", df$cleaned) #31
      df$cleaned <- gsub("dertig", "30", df$cleaned) #30
      #20
      df$cleaned <- gsub("negen en twintig", "29", df$cleaned); df$cleaned <- gsub("negenentwintig", "29", df$cleaned) #29
      df$cleaned <- gsub("acht en twintig", "28", df$cleaned); df$cleaned <- gsub("achtentwintig", "28", df$cleaned) #28
      df$cleaned <- gsub("zeven en twintig", "27", df$cleaned); df$cleaned <- gsub("zevenentwintig", "27", df$cleaned) #27
      df$cleaned <- gsub("zes en twintig", "26", df$cleaned); df$cleaned <- gsub("zesentwintig", "26", df$cleaned) #26
      df$cleaned <- gsub("vijf en twintig", "25", df$cleaned); df$cleaned <- gsub("vijfentwintig", "25", df$cleaned) #25
      df$cleaned <- gsub("vier en twintig", "24", df$cleaned); df$cleaned <- gsub("vierentwintig", "24", df$cleaned) #24
      df$cleaned <- gsub("drie en twintig", "23", df$cleaned); df$cleaned <- gsub("drieentwintig", "23", df$cleaned) #23
      df$cleaned <- gsub("twee en twintig", "22", df$cleaned); df$cleaned <- gsub("tweeentwintig", "22", df$cleaned) #22
      df$cleaned <- gsub("een en twintig", "21", df$cleaned); df$cleaned <- gsub("eenentwintig", "21", df$cleaned) #21
      df$cleaned <- gsub("twintig", "20", df$cleaned) #20
      #10
      df$cleaned <- gsub("negentien", "19", df$cleaned); df$cleaned <- gsub("ngentien", "19", df$cleaned) #19
      df$cleaned <- gsub("achttien", "18", df$cleaned); df$cleaned <- gsub("acttien", "18", df$cleaned) #18
      df$cleaned <- gsub("zeventien", "17", df$cleaned) #17
      df$cleaned <- gsub("zestien", "16", df$cleaned) #16
      df$cleaned <- gsub("vijftien", "15", df$cleaned) #15
      df$cleaned <- gsub("veertien", "14", df$cleaned) #14
      df$cleaned <- gsub("dertien", "13", df$cleaned) #13
      df$cleaned <- gsub("twaalf", "12", df$cleaned) #12
      df$cleaned <- gsub("elf ", "11 ", df$cleaned) #11
      df$cleaned <- gsub("tien", "10", df$cleaned) #10
      #0
      df$cleaned <- gsub("negen", "9", df$cleaned) #9
      df$cleaned <- gsub("acht ", "8 ", df$cleaned); df$cleaned <- gsub(" acht", " 8", df$cleaned) #8
      df$cleaned <- gsub("zeven ", "7 ", df$cleaned); df$cleaned <- gsub("z\\\\even ", "7 ", df$cleaned); df$cleaned <- gsub(" zeven", " 7", df$cleaned); df$cleaned <- gsub("zevenen", "7 en", df$cleaned)  #7
      df$cleaned <- gsub("zes", "6", df$cleaned) #6
      df$cleaned <- gsub("vijf", "5", df$cleaned); df$cleaned <- gsub("vif", "5", df$cleaned); df$cleaned <- gsub("vjif", "5", df$cleaned); df$cleaned <- gsub("vijd", "5", df$cleaned) #5
      df$cleaned <- gsub("vier en deels", "kwart", df$cleaned); df$cleaned <- gsub("vier en deel", "kwart", df$cleaned) #1/4
      df$cleaned <- gsub("vierendeels", "kwart", df$cleaned); df$cleaned <- gsub("vierendeel", "kwart", df$cleaned); df$cleaned <- gsub("vieren deels", "kwart", df$cleaned) #1/4
      df$cleaned <- gsub("vierde", "kwart", df$cleaned) #1/4
      df$cleaned <- gsub("vier", "4", df$cleaned); df$cleaned <- gsub("viet", "4", df$cleaned); df$cleaned <- gsub("viier", "4", df$cleaned); df$cleaned <- gsub("vir", "4", df$cleaned) #4
      df$cleaned <- gsub("drie", "3", df$cleaned) #3
      df$cleaned <- gsub("1 tweede", "half", df$cleaned); df$cleaned <- gsub("een tweede", "een half", df$cleaned) #1/2
      df$cleaned <- gsub("twee ", "2 ", df$cleaned); df$cleaned <- gsub("twwee ", "2 ", df$cleaned); df$cleaned <- gsub("tweeen", "2 en", df$cleaned) #2
      #save 1 for later
    #fractions
      #outdated
      df$month <- ifelse(grepl("kwarthalf", df$cleaned), 9, df$month) #3/4
      df$cleaned <- ifelse(grepl("kwarthalf", df$cleaned), "",df$cleaned) #3/4
      df$year <- ifelse(grepl("derdehalf", df$cleaned), 1, df$year) #3/2
      df$month <- ifelse(grepl("derdehalf", df$cleaned), 6, df$month) #3/2
      df$cleaned <- ifelse(grepl("derdehalf", df$cleaned), "",df$cleaned) #3/2
      #1/24
      df$day <- ifelse(grepl("24ste", df$cleaned), NA, df$day)
      df$cleaned <- ifelse(grepl("24ste", df$cleaned), "",df$cleaned)
      #1/4
      df$cleaned <- gsub("een kwart", "kwart", df$cleaned)
      #3/4
      df$cleaned <- gsub("3kwart", "3 kwart", df$cleaned)
      #
      df$year <- ifelse(grepl("een en 3 kwart", df$cleaned) | grepl("1 en 3 kwart", df$cleaned) | grepl("1 3 kwart", df$cleaned), "1", df$year);  #1 3/4
      df$month <- ifelse(grepl("een en 3 kwart", df$cleaned) | grepl("1 en 3 kwart", df$cleaned) | grepl("1 3 kwart", df$cleaned), "9", df$month) #1 3/4
      df$cleaned <- ifelse(grepl("een en 3 kwart", df$cleaned) | grepl("1 en 3 kwart", df$cleaned) | grepl("1 3 kwart", df$cleaned), "", df$cleaned) #1 3/4
      #
      df$year <- ifelse(grepl("2 en 3 kwart", df$cleaned) | grepl("2 3 kwart", df$cleaned), "1", df$year);  #2 3/4
      df$month <- ifelse(grepl("2 en 3 kwart", df$cleaned) | grepl("2 3 kwart", df$cleaned), "9", df$month) #2 3/4
      df$cleaned <- ifelse(grepl("2 en 3 kwart", df$cleaned) | grepl("2 3 kwart", df$cleaned), "", df$cleaned) #2 3/4
      #
      df$year <- ifelse(grepl("3 en 3 kwart", df$cleaned) | grepl("3 3 kwart", df$cleaned), "1", df$year);  #3 3/4
      df$month <- ifelse(grepl("3 en 3 kwart", df$cleaned) | grepl("3 3 kwart", df$cleaned), "9", df$month) #3 3/4
      df$cleaned <- ifelse(grepl("3 en 3 kwart", df$cleaned) | grepl("3 3 kwart", df$cleaned), "", df$cleaned) #3 3/4
      #
      df$year <- ifelse(grepl("4 en 3 kwart", df$cleaned) | grepl("4 3 kwart", df$cleaned), "1", df$year);  #4 3/4
      df$month <- ifelse(grepl("4 en 3 kwart", df$cleaned) | grepl("4 3 kwart", df$cleaned), "9", df$month) #4 3/4
      df$cleaned <- ifelse(grepl("4 en 3 kwart", df$cleaned) | grepl("4 3 kwart", df$cleaned), "", df$cleaned) #4 3/4
      #
      df$year <- ifelse(grepl("5 en 3 kwart", df$cleaned) | grepl("5 3 kwart", df$cleaned), "1", df$year);  #5 3/4
      df$month <- ifelse(grepl("5 en 3 kwart", df$cleaned) | grepl("5 3 kwart", df$cleaned), "9", df$month) #5 3/4
      df$cleaned <- ifelse(grepl("5 en 3 kwart", df$cleaned) | grepl("5 3 kwart", df$cleaned), "", df$cleaned) #5 3/4
      #
      df$year <- ifelse(grepl("6 en 3 kwart", df$cleaned) | grepl("6 3 kwart", df$cleaned), "1", df$year);  #6 3/4
      df$month <- ifelse(grepl("6 en 3 kwart", df$cleaned) | grepl("6 3 kwart", df$cleaned), "9", df$month) #6 3/4
      df$cleaned <- ifelse(grepl("6 en 3 kwart", df$cleaned) | grepl("6 3 kwart", df$cleaned), "", df$cleaned) #6 3/4
      #
      df$year <- ifelse(grepl("7 en 3 kwart", df$cleaned) | grepl("7 3 kwart", df$cleaned), "1", df$year);  #7 3/4
      df$month <- ifelse(grepl("7 en 3 kwart", df$cleaned) | grepl("7 3 kwart", df$cleaned), "9", df$month) #7 3/4
      df$cleaned <- ifelse(grepl("7 en 3 kwart", df$cleaned) | grepl("7 3 kwart", df$cleaned), "", df$cleaned) #7 3/4
      #
      df$month <- ifelse(grepl("3 kwart", df$cleaned), "9", df$month) #7 3/4
      df$cleaned <- ifelse(grepl("3 kwart", df$cleaned), "", df$cleaned) #7 3/4
      #5/4
      df$year <- ifelse(grepl("5 kwart", df$cleaned), "1", df$year);  #5/4
      df$month <- ifelse(grepl("5 kwart", df$cleaned), "3", df$month) #5/4
      df$cleaned <- ifelse(grepl("5 kwart", df$cleaned), "", df$cleaned) #5/4
      #7/4
      df$year <- ifelse(grepl("7 kwart", df$cleaned) | grepl("zevenkwart", df$cleaned), "1", df$year);  #7/4
      df$month <- ifelse(grepl("7 kwart", df$cleaned) | grepl("zevenkwart", df$cleaned), "9", df$month) #7/4
      df$cleaned <- ifelse(grepl("7 kwart", df$cleaned) | grepl("zevenkwart", df$cleaned), "", df$cleaned) #7/4
      #1/4
      df$year <- ifelse(grepl("een en kwart", df$cleaned) | grepl("1 en kwart", df$cleaned) | grepl("1 en 1 kwart", df$cleaned) | grepl("1  en 1 kwart", df$cleaned), "1", df$year)  #1 1/4
      df$month <- ifelse(grepl("een en kwart", df$cleaned) | grepl("1 en kwart", df$cleaned) | grepl("1 en 1 kwart", df$cleaned) | grepl("1  en 1 kwart", df$cleaned), "3", df$month) #1 1/4
      df$cleaned <- ifelse(grepl("een en kwart", df$cleaned) | grepl("1 en kwart", df$cleaned) | grepl("1 en 1 kwart", df$cleaned) | grepl("1  en 1 kwart", df$cleaned), "", df$cleaned) #1 1/4
      #
      df$year <- ifelse(grepl("kwart", df$cleaned) & nchar(gsub("\\D", "", substr(df$cleaned,1,1)))==1 , as.numeric(gsub("\\D", "", substr(df$cleaned,1,2))), df$year)
      df$month <- ifelse(grepl("kwart", df$cleaned), "3", df$month) #1/4
      df$cleaned <- ifelse(grepl("kwart", df$cleaned), "", df$cleaned) #1/4
      #2/3
      df$month <- ifelse(grepl("tweederde", df$cleaned) | grepl("2 derde", df$cleaned), "8", df$month) #2/3
      df$cleaned <- ifelse(grepl("tweederde", df$cleaned) | grepl("2 derde", df$cleaned), "", df$cleaned) #2/3
      #1/3
      df$year <- ifelse(grepl("1 en een derde", df$cleaned) | grepl("1 en 1 derde", df$cleaned), "4", df$year) #1 1/3
      df$month <- ifelse(grepl("1 en een derde", df$cleaned) | grepl("1 en 1 derde", df$cleaned), "4", df$month) #1 1/3
      df$cleaned <- ifelse(grepl("1 en een derde", df$cleaned) | grepl("1 en 1 derde", df$cleaned), "", df$cleaned) #1 1/3
      #
      df$year <- ifelse(grepl("2 en een derde", df$cleaned) | grepl("2 en 1 derde", df$cleaned), "4", df$year) #2 1/3
      df$month <- ifelse(grepl("2 en een derde", df$cleaned) | grepl("2 en 1 derde", df$cleaned), "4", df$month) #2 1/3
      df$cleaned <- ifelse(grepl("2 en een derde", df$cleaned) | grepl("2 en 1 derde", df$cleaned), "", df$cleaned) #2 1/3
      #
      df$year <- ifelse(grepl("3 en een derde", df$cleaned) | grepl("3 en 1 derde", df$cleaned), "4", df$year) #3 1/3
      df$month <- ifelse(grepl("3 en een derde", df$cleaned) | grepl("3 en 1 derde", df$cleaned), "4", df$month) #3 1/3
      df$cleaned <- ifelse(grepl("3 en een derde", df$cleaned) | grepl("3 en 1 derde", df$cleaned), "", df$cleaned) #3 1/3
      #
      df$year <- ifelse(grepl("4 en een derde", df$cleaned) | grepl("4 en 1 derde", df$cleaned), "4", df$year) #4 1/3
      df$month <- ifelse(grepl("4 en een derde", df$cleaned) | grepl("4 en 1 derde", df$cleaned), "4", df$month) #4 1/3
      df$cleaned <- ifelse(grepl("4 en een derde", df$cleaned) | grepl("4 en 1 derde", df$cleaned), "", df$cleaned) #4 1/3
      #
      df$year <- ifelse(grepl("5 en een derde", df$cleaned) | grepl("5 en 1 derde", df$cleaned), "4", df$year) #5 1/3
      df$month <- ifelse(grepl("5 en een derde", df$cleaned) | grepl("5 en 1 derde", df$cleaned), "4", df$month) #5 1/3
      df$cleaned <- ifelse(grepl("5 en een derde", df$cleaned) | grepl("5 en 1 derde", df$cleaned), "", df$cleaned) #5 1/3
      #
      df$year <- ifelse(grepl("6 en een derde", df$cleaned) | grepl("6 en 1 derde", df$cleaned), "4", df$year) #6 1/3
      df$month <- ifelse(grepl("6 en een derde", df$cleaned) | grepl("6 en 1 derde", df$cleaned), "4", df$month) #6 1/3
      df$cleaned <- ifelse(grepl("6 en een derde", df$cleaned) | grepl("6 en 1 derde", df$cleaned), "", df$cleaned) #6 1/3
      #
      df$year <- ifelse(grepl("7 en een derde", df$cleaned) | grepl("7 en 1 derde", df$cleaned), "4", df$year) #7 1/3
      df$month <- ifelse(grepl("7 en een derde", df$cleaned) | grepl("7 en 1 derde", df$cleaned), "4", df$month) #7 1/3
      df$cleaned <- ifelse(grepl("7 en een derde", df$cleaned) | grepl("7 en 1 derde", df$cleaned), "", df$cleaned) #7 1/3
      #
      df$month <- ifelse(grepl("een derde", df$cleaned) | grepl("1 derde", df$cleaned), "4", df$month) #1/3
      df$cleaned <- ifelse(grepl("een derde", df$cleaned) | grepl("1 derde", df$cleaned), "", df$cleaned) #1/3
      #1/2
      df$cleaned <- gsub("anderhalf", 1.5, df$cleaned)
      df$cleaned <- gsub("anderhalve", 1.5, df$cleaned)
      df$cleaned <- gsub("ander half", 1.5, df$cleaned)
      df$cleaned <- gsub("een en een half", 1.5, df$cleaned)
      df$cleaned <- gsub("een en een halve", 1.5, df$cleaned)
      df$cleaned <- gsub("een en eenhalve", 1.5, df$cleaned)
      df$cleaned <- gsub("een en eenhalf", 1.5, df$cleaned)
      df$cleaned <- gsub("1  en 1 half", 1.5, df$cleaned)
      df$cleaned <- gsub("1 een half", 1.5, df$cleaned)
      df$cleaned <- gsub("1en een half", 1.5, df$cleaned)
      df$cleaned <- gsub("een en half", 1.5, df$cleaned)
      df$cleaned <- gsub("een en halve", 1.5, df$cleaned)
      df$cleaned <- gsub("een en half", 1.5, df$cleaned)
      df$cleaned <- gsub("een en halve", 1.5, df$cleaned)
      #
      df$cleaned <- gsub(" en eeen halve", ".5", df$cleaned)
      df$cleaned <- gsub(" en een halve", ".5", df$cleaned)
      df$cleaned <- gsub(" en een half", ".5", df$cleaned)
      df$cleaned <- gsub(" en 1 half", ".5", df$cleaned)
      df$cleaned <- gsub(" en 1 halve", ".5", df$cleaned)
      df$cleaned <- gsub(" en eenhalf", ".5", df$cleaned)
      df$cleaned <- gsub(" eneenhalf", ".5", df$cleaned)
      df$cleaned <- gsub(" eneenhalve", ".5", df$cleaned)
      df$cleaned <- gsub("eneenhalve", ".5", df$cleaned)
      df$cleaned <- gsub("een een halve", ".5", df$cleaned)
      df$cleaned <- gsub("en een half", ".5", df$cleaned)
      df$cleaned <- gsub("en half", ".5", df$cleaned)
      df$cleaned <- gsub("en halve", ".5", df$cleaned)
      df$cleaned <- gsub("een half", "0.5", df$cleaned)
      df$cleaned <- gsub("1 half", "0.5", df$cleaned)
      df$cleaned <- gsub("een halve", "0.5", df$cleaned)
      df$cleaned <- gsub("1 halve", "0.5", df$cleaned)
      df$cleaned <- gsub(".5 half", ".5", df$cleaned)
      df$cleaned <- gsub(".5 halve", ".5", df$cleaned)
      df$cleaned <- ifelse(grepl("\\d halve", df$cleaned), gsub(" halve", ".5", df$cleaned), df$cleaned)
      df$cleaned <- gsub("half", "0.5", df$cleaned)
      df$cleaned <- gsub("halve", "0.5", df$cleaned)
      #
      df$cleaned <- gsub("een \\.5", ".5", df$cleaned)
      df$cleaned <- gsub("een \\.5", ".5", df$cleaned)
      df$cleaned <- ifelse(grepl("\\d en \\.5", df$cleaned), gsub(" en \\.5", ".5", df$cleaned), df$cleaned)
      df$cleaned <- gsub("en \\.5", ".5", df$cleaned)
      df$cleaned <- ifelse(grepl("\\d \\.5", df$cleaned), gsub(" \\.5", ".5", df$cleaned), df$cleaned)
      df$cleaned <- gsub(" \\.5", " 0.5", df$cleaned)
      df$cleaned <- ifelse(grepl("\\.5", substr(df$cleaned,1,2)), gsub("\\.5", "0.5", df$cleaned), df$cleaned)
      #
      df$cleaned <- gsub("e\\.5", "0.5", df$cleaned)
    #een
      df$cleaned <- gsub("min een dag", "", df$cleaned) #day
      df$cleaned <- gsub("ee dag", "1 dag", df$cleaned) #day
      df$cleaned <- gsub("een dag", "1 dag", df$cleaned) #day
      df$cleaned <- gsub("eene dag", "1 dag", df$cleaned) #day
      df$cleaned <- gsub("eenen dag", "1 dag", df$cleaned) #day
      df$cleaned <- gsub("min een week", "", df$cleaned) #week
      df$cleaned <- gsub("een week", "1 week", df$cleaned) #week
      df$cleaned <- gsub("eene week", "1 week", df$cleaned) #week
      df$cleaned <- gsub("eenen week", "1 week", df$cleaned) #week
      df$cleaned <- gsub("min een maand", "", df$cleaned) #month
      df$cleaned <- gsub("een maand", "1 maand", df$cleaned) #month
      df$cleaned <- gsub("een maad", "1 maand", df$cleaned) #month
      df$cleaned <- gsub("eene maand", "1 maand", df$cleaned) #month
      df$cleaned <- gsub("eenen maand", "1 maand", df$cleaned) #month
      df$cleaned <- gsub("min een jaar", "", df$cleaned) #year
      df$cleaned <- gsub("een jaar", "1 jaar", df$cleaned) #year
      df$cleaned <- gsub("eene jaar", "1 jaar", df$cleaned) #year
      df$cleaned <- gsub("eenen jaar", "1 jaar", df$cleaned) #year
    #remove redundant information
      #oud
      df$cleaned <- ifelse(grepl("oud ", df$cleaned) & grepl("\\d", df$cleaned)==F, "", df$cleaned); df$cleaned <- gsub("oud", "", df$cleaned)  #remove oud [old] without numerical entry
      df$cleaned <- gsub("oud ", "", df$cleaned); df$cleaned <- gsub(" oud", "", df$cleaned) #remove oud [old]
    #circa
      df$cleaned <- gsub("beneden ", "", df$cleaned) #remove beneden [under]
      df$cleaned <- gsub(" \\(circa\\)", "", df$cleaned); df$cleaned <- gsub(" \\(circa.\\)", "", df$cleaned); df$cleaned <- gsub("\\(circa\\)", "", df$cleaned); df$cleaned <- gsub(" circa", "", df$cleaned) #remove circa [circa]
      df$cleaned <- gsub("cica ", "", df$cleaned)
      df$cleaned <- ifelse(grepl("cir", df$cleaned), sub("^([^0-9.]+)", '', df$cleaned), df$cleaned) #remove variations circa [circa]
      df$cleaned <- ifelse(grepl("ca", df$cleaned) & grepl("\\d", df$cleaned)==F, "", df$cleaned) #remove ca [circa] without numerical entry
      df$cleaned <- gsub("ca\\. ", "", df$cleaned); df$cleaned <- gsub("ca\\.", "", df$cleaned); df$cleaned <- gsub("c\\. ", "", df$cleaned) #remove ca. [circa]
      df$cleaned <- gsub(" ca", "", df$cleaned); df$cleaned <- gsub(" \\(ca\\)", "", df$cleaned); df$cleaned <- gsub(" \\(ca.\\)", "", df$cleaned) #remove ca [circa]
      df$cleaned <- gsub("ca ", "", df$cleaned); df$cleaned <- gsub("ca", "", df$cleaned) #remove ca [circa]
      df$cleaned <- gsub("in de ", "", df$cleaned) #remove juist [exactly]
      df$cleaned <- gsub("juist ", "", df$cleaned) #remove juist [exactly]
      df$cleaned <- gsub("om de ", "", df$cleaned) #remove om de [about]
      df$cleaned <- gsub("omstreeks ", "", df$cleaned); df$cleaned <- gsub(" omstreeks", "", df$cleaned) #remove omstreeks [about]
      df$cleaned <- gsub(" omtrent", "", df$cleaned); df$cleaned <- gsub(" \\(omtrent\\)", "", df$cleaned) #remove omtrent [roughly]
      df$cleaned <- ifelse(grepl("omt", df$cleaned), sub("^([^0-9.]+)", '', df$cleaned), df$cleaned) #remove misspelled ongeveer [about]
      df$cleaned <- ifelse(grepl("moment", df$cleaned), "1 dag", df$cleaned) #change een moment [a moment] to 1 day
      df$cleaned <- gsub(" ongeveer", "", df$cleaned); df$cleaned <- gsub(" \\(ongeveer\\)", "", df$cleaned) #remove ongeveer [about]
      df$cleaned <- ifelse(grepl("ong", df$cleaned) & grepl("\\d", df$cleaned)==F, "", df$cleaned) #remove ongeveer [about] without numerical entry
      df$cleaned <- ifelse(grepl("ong", df$cleaned), sub("^([^0-9.]+)", '', df$cleaned), df$cleaned) #remove misspelled ongeveer [about]
      df$cleaned <- gsub("thans ", "", df$cleaned) #remove thans [now]
      df$cleaned <- gsub(" vermoedelijk", "", df$cleaned); df$cleaned <- gsub(" \\(vermoedelijk", "", df$cleaned) #remove vermoedelijk
      df$cleaned <- gsub("volgens monsterrol", "", df$cleaned) #volgens monsterrol [form says]
      df$cleaned <- ifelse(grepl("bi", substr(df$cleaned,1,2)), sub("^([^0-9.]+)", '', df$cleaned), df$cleaned) #remove starting bijna [about]
      df$cleaned <- gsub("bijna ", "", df$cleaned); df$cleaned <- gsub("bijna", "", df$cleaned); df$cleaned <- gsub("bijma", "", df$cleaned); df$cleaned <- gsub("beina", "", df$cleaned) #remove bijna [about]
      df$cleaned <- gsub("nabij ", "", df$cleaned) #remove nabij [near]
      df$cleaned <- ifelse(grepl("ru", substr(df$cleaned,1,3)), sub("^([^0-9.]+)", '', df$cleaned), df$cleaned) #remove starting ruim [more than]
      df$cleaned <- ifelse(grepl("uim", substr(df$cleaned,1,6)), sub("^([^0-9.]+)", '', df$cleaned), df$cleaned) #remove starting ruim [more than]
      df$cleaned <- gsub("ruim", "", df$cleaned)
      df$cleaned <- gsub("rond ", "", df$cleaned)
      df$cleaned <- gsub("nagenoeg ", "", df$cleaned)
      df$cleaned <- gsub("zowat ", "", df$cleaned) #zowat [almost]
      df$cleaned <- ifelse(grepl("verm", df$cleaned), sub("^([^0-9.]+)", '', df$cleaned), df$cleaned) #remove variations vermoedelijk [most likely]
      df$cleaned <- ifelse(substr(df$cleaned,1,1)=="'", substr(df$cleaned,2,nchar(df$cleaned)), df$cleaned) #remove leading '
      df$cleaned <- ifelse(substr(df$cleaned,1,1)=="`", substr(df$cleaned,2,nchar(df$cleaned)), df$cleaned) #remove leading ``
      df$cleaned <- gsub("\\+\\- ", "", df$cleaned) #+/-
      df$cleaned <- gsub("\\+/\\- ", "", df$cleaned) #+/-
      df$cleaned <- gsub("\\+/ \\- ", "", df$cleaned) #+/-
      df$cleaned <- gsub("plus minus ", "", df$cleaned) #+/-
      df$cleaned <- gsub("\\+", "en", df$cleaned) #+
      df$cleaned <- gsub("plus", "en", df$cleaned) #+
    #clean jaar
      df$cleaned <- ifelse(substr(df$cleaned,1,4)=="jaar", gsub("jaar", "1 jaar", df$cleaned), df$cleaned)
      df$cleaned <- ifelse(df$cleaned=="dag", "1 dag", df$cleaned)
    #clean textless fields
      df$cleaned <- ifelse(grepl("\\d", df$cleaned)==F, "", df$cleaned)
      df$year <- ifelse(df$cleaned=="op 4 dagen na 1", 1, df$year)
      df$cleaned <- ifelse(df$cleaned=="op 4 dagen na 1", "", df$cleaned)
      df$month <- ifelse(df$cleaned==".5 jaar", 6, df$month)
      df$cleaned <- ifelse(df$cleaned==".5 jaar", "", df$cleaned)
    #remove months
      df$cleaned <- ifelse(grepl("jan", df$cleaned),"",df$cleaned) #remove entries mentioning January
      df$cleaned <- ifelse(grepl("feb", df$cleaned),"",df$cleaned) #remove entries mentioning February
      df$cleaned <- ifelse(grepl("maart", df$cleaned),"",df$cleaned) #remove entries mentioning March
      df$cleaned <- ifelse(grepl("mrt", df$cleaned),"",df$cleaned) #remove entries mentioning March
      df$cleaned <- ifelse(grepl("apr", df$cleaned),"",df$cleaned) #remove entries mentioning April
      df$cleaned <- ifelse(grepl("mei", df$cleaned),"",df$cleaned) #remove entries mentioning May
      df$cleaned <- ifelse(grepl("jun", df$cleaned),"",df$cleaned) #remove entries mentioning June
      df$cleaned <- ifelse(grepl("jul", df$cleaned),"",df$cleaned) #remove entries mentioning July
      df$cleaned <- ifelse(grepl("aug", df$cleaned),"",df$cleaned) #remove entries mentioning August
      df$cleaned <- ifelse(grepl("sep", df$cleaned),"",df$cleaned) #remove entries mentioning September
      df$cleaned <- ifelse(grepl("okt", df$cleaned),"",df$cleaned) #remove entries mentioning October
      df$cleaned <- ifelse(grepl("nov", df$cleaned),"",df$cleaned) #remove entries mentioning November
      df$cleaned <- ifelse(grepl("dec", df$cleaned),"",df$cleaned) #remove entries mentioning December
    #duplicated information on age
      df$cleaned <- ifelse(grepl("\\d{4}", df$cleaned) & as.numeric(substr(gsub("\\D", "", df$cleaned),1,2))==as.numeric(substr(gsub("\\D", "", df$cleaned),3,4)), 
                           substr(gsub("\\D", "", df$cleaned),1,2), df$cleaned) #remove duplicated numbers
      df$cleaned <- ifelse(grepl("\\d{4}", df$cleaned) & as.numeric(substr(gsub("\\D", "", df$cleaned),1,2))+1==as.numeric(substr(gsub("\\D", "", df$cleaned),3,4)), 
                           substr(gsub("\\D", "", df$cleaned),1,2), df$cleaned) #remove duplicated numbers with 1 year positive difference
      df$cleaned <- ifelse(grepl("\\d{4}", df$cleaned) & as.numeric(substr(gsub("\\D", "", df$cleaned),1,2))-1==as.numeric(substr(gsub("\\D", "", df$cleaned),3,4)), 
                           substr(gsub("\\D", "", df$cleaned),1,2), df$cleaned) #remove duplicated numbers with 1 year negative difference
      df$cleaned <- ifelse(grepl("\\d{4}", df$cleaned),"", df$cleaned) #delete remaining duplicated numbers
    #range with 1 year
      df$cleaned <- ifelse(grepl("of", df$cleaned), paste0(substr(df$cleaned,1,2), " jaar"), df$cleaned)
    #numbers only
      df$cleaned <- ifelse(substr(df$cleaned,1,1)==" ", substr(df$cleaned, 2, nchar(df$cleaned)), df$cleaned) #delete trailing space
      df$cleaned <- ifelse(grepl("\\D", df$cleaned)==F & substr(df$cleaned,1,1)=="0", "", df$cleaned) #delete rows with leading 0s
      df$year <- ifelse(grepl("\\D", df$cleaned)==F & df$cleaned!="", df$cleaned, df$year)
      df$cleaned <- ifelse(grepl("\\D", df$cleaned)==F & df$cleaned!="", "", df$cleaned)
    #.5
      #year only
      df$year <- ifelse(grepl("\\.5", df$cleaned) & grepl("j",df$cleaned) & grepl("m",df$cleaned)==F, gsub("\\D", "", sub("\\.5.*", '', df$cleaned)), df$year)
      df$month <- ifelse(grepl("\\.5", df$cleaned) & grepl("j",df$cleaned) & grepl("m",df$cleaned)==F, 6, df$month)
      df$cleaned <- ifelse(grepl("\\.5", df$cleaned) & grepl("j",df$cleaned) & grepl("m",df$cleaned)==F, "", df$cleaned)
      #year + month
      df$week <- ifelse(grepl("\\.5", df$cleaned) & grepl("j",df$cleaned) & grepl("m",df$cleaned), 2, df$week)
      df$cleaned <- ifelse(grepl("\\.5", df$cleaned) & grepl("j",df$cleaned) & grepl("m",df$cleaned), gsub("\\.5", "", df$cleaned), df$cleaned)
      #week
      df$week <- ifelse(grepl("\\.5", df$cleaned) & grepl("w",df$cleaned), gsub("\\D", "", sub("\\.5.*", '', df$cleaned)), df$week)
      df$day <- ifelse(grepl("\\.5", df$cleaned) & grepl("w",df$cleaned), 3, df$day)
      df$cleaned <- ifelse(grepl("\\.5", df$cleaned) & grepl("w",df$cleaned), "", df$cleaned)
      #day
      df$day <- ifelse(grepl("\\.5", df$cleaned) & grepl("g",df$cleaned), as.numeric(gsub("\\D","",df$cleaned))+1, df$day)
      df$cleaned <- ifelse(grepl("\\.5", df$cleaned) & grepl("g",df$cleaned), "", df$cleaned)
      #month
      df$week <- ifelse(grepl("\\.5", df$cleaned) & grepl("m",df$cleaned), 2, df$week)
      df$cleaned <- ifelse(grepl("\\.5", df$cleaned) & grepl("m",df$cleaned), gsub("\\.5", "", df$cleaned), df$cleaned)
      #no ymwd mentioned
      df$year <- ifelse(grepl("\\.5", df$cleaned), gsub("\\D", "", sub("\\.5.*", '', df$cleaned)), df$year)
      df$month <- ifelse(grepl("\\.5", df$cleaned), 6, df$month)
      df$cleaned <- ifelse(grepl("\\.5", df$cleaned), "", df$cleaned)
    #clean jaar [year]
      df$cleaned <- ifelse(grepl("\\d r", df$cleaned), gsub(" r", " jaar", df$cleaned), df$cleaned)
      df$cleaned <- gsub("gaar", "jaar", df$cleaned)
      df$cleaned <- gsub("jhaar", "jaar", df$cleaned)
      df$cleaned <- gsub("haar", "jaar", df$cleaned)
      df$cleaned <- gsub("iaar", "jaar", df$cleaned)
      df$cleaned <- gsub("jkaar", "jaar", df$cleaned)
      df$cleaned <- gsub("kaar", "jaar", df$cleaned)
      df$cleaned <- gsub("jlaar", "jaar", df$cleaned)
      df$cleaned <- gsub("laar", "jaar", df$cleaned)
      df$cleaned <- gsub("j aar", "jaar", df$cleaned)
      df$cleaned <- gsub(" aar", "jaar", df$cleaned)
      df$cleaned <- gsub("haren", "jaar", df$cleaned)
      df$cleaned <- gsub("iaren", "jaar", df$cleaned)
      df$cleaned <- gsub("karen", "jaar", df$cleaned)
      df$cleaned <- gsub("laren", "jaar", df$cleaned)
      df$cleaned <- gsub("jaar4", "jaar", df$cleaned)
      df$cleaned <- gsub("jaar5", "jaar", df$cleaned)
    #clean maand [month]
      df$cleaned <- gsub("naand", "maand", df$cleaned)
      df$cleaned <- gsub("m aand", "maand", df$cleaned)
      df$cleaned <- gsub(" aand", "maand", df$cleaned)
      df$cleaned <- gsub(" nnd", " mnd", df$cleaned)
      df$cleaned <- gsub("m nd", " mnd", df$cleaned)
      df$cleaned <- gsub(" nd", " mnd", df$cleaned)
    #clean dag [day]
      df$cleaned <- gsub("dagem", "dagen", df$cleaned)
      df$cleaned <- ifelse(grepl("m", df$cleaned) & grepl("dag", sub("m.*", '', df$cleaned)), sub("dagen", "jaren", df$cleaned), df$cleaned)
      df$cleaned <- ifelse(grepl("m", df$cleaned) & grepl("dag", sub("m.*", '', df$cleaned)), sub("dgn", "jaren", df$cleaned), df$cleaned)
      df$cleaned <- ifelse(grepl("dagen\\(", df$cleaned), sub("\\(.*", '', df$cleaned), df$cleaned)
      #clean standardised entries
      #year
      df$year <- ifelse(grepl("j", df$cleaned), gsub("\\D", "", sub("j.*", '', df$cleaned)), df$year)
      df$cleaned <- ifelse(grepl("j", df$cleaned), sub(".*j", '', df$cleaned), df$cleaned)
      df$cleaned <- ifelse(grepl("\\d", df$cleaned)==F, "", df$cleaned)
      df$year <- ifelse(is.na(df$year) & grepl("\\d,", df$cleaned), gsub("\\D", "", sub(",.*", '', df$cleaned)), df$year)
      df$cleaned <- ifelse(is.na(df$year) & grepl("\\d,", df$cleaned), sub(".*,", '', df$cleaned), df$cleaned)
      df$year <- ifelse(grepl("\\d\\.", substr(df$cleaned,1,3)), gsub("\\D", "", substr(df$cleaned,1,2)), df$year)
      df$cleaned <- ifelse(grepl("\\d\\.", substr(df$cleaned,1,3)), substr(df$cleaned,4, nchar(df$cleaned)), df$cleaned)
      #year not mentioned, but month is
      df$year <- ifelse(grepl("\\d en \\d m", df$cleaned), gsub("\\D", "", sub("en.*", '', df$cleaned)), df$year)
      df$cleaned <- ifelse(grepl("\\d en \\d m", df$cleaned), sub(".*en", '', df$cleaned), df$cleaned)
      df$year <- ifelse(grepl("\\d en \\d\\d m", df$cleaned), gsub("\\D", "", sub("en.*", '', df$cleaned)), df$year)
      df$cleaned <- ifelse(grepl("\\d en \\d\\d m", df$cleaned), sub(".*en", '', df$cleaned), df$cleaned)
      df$year <- ifelse(grepl("\\d en  \\d m", df$cleaned), gsub("\\D", "", sub("en.*", '', df$cleaned)), df$year)
      df$cleaned <- ifelse(grepl("\\d en  \\d m", df$cleaned), sub(".*en", '', df$cleaned), df$cleaned)
      df$year <- ifelse(grepl("\\d en  \\d\\d m", df$cleaned), gsub("\\D", "", sub("en.*", '', df$cleaned)), df$year)
      df$cleaned <- ifelse(grepl("\\d en  \\d\\d m", df$cleaned), sub(".*en", '', df$cleaned), df$cleaned)
      df$year <- ifelse(grepl("\\d en \\dm", df$cleaned), gsub("\\D", "", sub("en.*", '', df$cleaned)), df$year)
      df$cleaned <- ifelse(grepl("\\d en \\dm", df$cleaned), sub(".*en", '', df$cleaned), df$cleaned)
      df$year <- ifelse(grepl("\\d en \\d\\dm", df$cleaned), gsub("\\D", "", sub("en.*", '', df$cleaned)), df$year)
      df$cleaned <- ifelse(grepl("\\d en \\d\\dm", df$cleaned), sub(".*en", '', df$cleaned), df$cleaned)
      df$year <- ifelse(grepl("\\d en\\d m", df$cleaned), gsub("\\D", "", sub("en.*", '', df$cleaned)), df$year)
      df$cleaned <- ifelse(grepl("\\d en\\d m", df$cleaned), sub(".*en", '', df$cleaned), df$cleaned)
      df$year <- ifelse(grepl("\\d en\\d\\d m", df$cleaned), gsub("\\D", "", sub("en.*", '', df$cleaned)), df$year)
      df$cleaned <- ifelse(grepl("\\d en\\d\\d m", df$cleaned), sub(".*en", '', df$cleaned), df$cleaned)
      df$year <- ifelse(grepl("\\d en\\dm", df$cleaned), gsub("\\D", "", sub("en.*", '', df$cleaned)), df$year)
      df$cleaned <- ifelse(grepl("\\d en\\dm", df$cleaned), sub(".*en", '', df$cleaned), df$cleaned)
      df$year <- ifelse(grepl("\\d en\\d\\dm", df$cleaned), gsub("\\D", "", sub("en.*", '', df$cleaned)), df$year)
      df$cleaned <- ifelse(grepl("\\d en\\d\\dm", df$cleaned), sub(".*en", '', df$cleaned), df$cleaned)
      #
      df$year <- ifelse(grepl("\\d \\d m", substr(df$cleaned,1,7)), gsub("\\D", "", sub(" .*", '', df$cleaned)), df$year)
      df$cleaned <- ifelse(grepl("\\d \\d m", substr(df$cleaned,1,7)), substr(df$cleaned, 3, nchar(df$cleaned)), df$cleaned)
      df$year <- ifelse(grepl("\\d \\d\\d m", substr(df$cleaned,1,7)), gsub("\\D", "", sub(" .*", '', df$cleaned)), df$year)
      df$cleaned <- ifelse(grepl("\\d \\d\\d m", substr(df$cleaned,1,7)), substr(df$cleaned, 3, nchar(df$cleaned)), df$cleaned)
      #
      df$cleaned <- ifelse(grepl("\\d en \\d", df$cleaned), "", df$cleaned) #deletes undefined units of time
      #month
      df$month <- ifelse(grepl("m", df$cleaned), gsub("\\D", "", sub("m.*", '', df$cleaned)), df$month)
      df$cleaned <- ifelse(grepl("m", df$cleaned), sub(".*m", '', df$cleaned), df$cleaned)
      df$cleaned <- ifelse(grepl("\\d", df$cleaned)==F, "", df$cleaned)
      #week
      df$week <- ifelse(grepl("w", df$cleaned), gsub("\\D", "", sub("w.*", '', df$cleaned)), df$week)
      df$cleaned <- ifelse(grepl("w", df$cleaned), sub(".*w", '', df$cleaned), df$cleaned)
      df$cleaned <- ifelse(grepl("\\d", df$cleaned)==F, "", df$cleaned)
      #day
      df$day <- ifelse(grepl("g", df$cleaned), gsub("\\D", "", sub("g.*", '', df$cleaned)), df$day)
      df$cleaned <- ifelse(grepl("g", df$cleaned), sub(".*g", '', df$cleaned), df$cleaned)
      df$cleaned <- ifelse(grepl("\\d", df$cleaned)==F, "", df$cleaned)
      #
      df$day <- ifelse(grepl("d", df$cleaned) & df$year==0, gsub("\\D", "", sub("d.*", '', df$cleaned)), df$day)
      df$cleaned <- ifelse(grepl("d", df$cleaned) & df$year==0, sub(".*d", '', df$cleaned), df$cleaned)
      df$cleaned <- ifelse(grepl("\\d", df$cleaned)==F, "", df$cleaned)
      #
      df$day <- ifelse(grepl("nd en ", df$cleaned), gsub("\\D", "", df$cleaned), df$day)
      df$cleaned <- ifelse(grepl("nd en", df$cleaned), "", df$cleaned)
      #
      df$day <- ifelse(df$cleaned!="" & grepl("j m w ", df$Var1), gsub("\\D", "", df$cleaned), df$day)
      df$cleaned <- ifelse(df$cleaned!="" & grepl("j m w ", df$Var1), "", df$cleaned)
    #clean remaining entries
      #year
      df$year <- ifelse(nchar(df$year)==4 & substr(df$year,1,2)==substr(df$year,3,4), substr(df$year,1,2), df$year)
      df$year <- ifelse(nchar(df$year)==2 & substr(df$year,1,1)=="0", substr(df$year,2,2), df$year)
      df$year <- ifelse(df$year=="000", 0, df$year)
      df$year <- as.numeric(df$year)
      df$year <- ifelse(df$year>120, NA, df$year)
      #month
      df$month <- as.numeric(df$month)
      df$month <- ifelse(!is.na(df$year) & df$month>11, NA, df$month)
      #day
      df$day <- as.numeric(df$day)
      df$day <- ifelse(!is.na(df$month) & df$day>30, NA, df$day)
      df$day <- ifelse(!is.na(df$week) & df$day>6, NA, df$day)
    #give 0 to NA y/m/w/d IF at last a y/m/w/d is available
      df$year <- ifelse(is.na(df$year) & !is.na(df$month) | is.na(df$year) & !is.na(df$week) | is.na(df$year) & !is.na(df$day), 0, df$year)
      df$month <- ifelse(is.na(df$month) & !is.na(df$year) | is.na(df$month) & !is.na(df$week) | is.na(df$month) & !is.na(df$day), 0, df$month)
      df$week <- ifelse(is.na(df$week) & !is.na(df$year) | is.na(df$week) & !is.na(df$week) | is.na(df$week) & !is.na(df$day), 0, df$week)
      df$day <- ifelse(is.na(df$day) & !is.na(df$year) | is.na(df$day) & !is.na(df$week) | is.na(df$day) & !is.na(df$day), 0, df$day)
    #give NA IF y/m/w/d are all 0
      df$year <- ifelse(df$year==0 & df$month==0 & df$week==0 & df$day==0, NA, df$year)
      df$month <- ifelse(df$year==0 & df$month==0 & df$week==0 & df$day==0, NA, df$month)
      df$week <- ifelse(df$year==0 & df$month==0 & df$week==0 & df$day==0, NA, df$week)
      df$day <- ifelse(df$year==0 & df$month==0 & df$week==0 & df$day==0, NA, df$day)
    #prepare merge
      df <- df[,c("Var1", "year", "month", "week", "day")]
      df[df==""] <- NA
      colnames(df) <- c("Var1", paste0(gsub(paste0(deparse(substitute(db)),"\\$")  , "", deparse(substitute(AgeVar))), c("_year", "_month", "_week", "_day")))
      df
    #merge new variable to db
      df <- merge(db, df, by.x=gsub(paste0(deparse(substitute(db)),"\\$")  , "", deparse(substitute(AgeVar))), by.y="Var1", all.x=T)
      df
    }
    
    
  #recode variables  
    #run functions on Birth certificates
    Birth <- clean_age(Birth, Birth$PR_AGE)
    Birth <- clean_age(Birth, Birth$PR_FTHR_AGE)
    Birth <- clean_age(Birth, Birth$PR_MTHR_AGE)
    #run functions on Marriage certificates
    Marriage <- clean_age(Marriage, Marriage$GROOM_AGE)
    Marriage <- clean_age(Marriage, Marriage$GROOM_FTHR_AGE)
    Marriage <- clean_age(Marriage, Marriage$GROOM_MTHR_AGE)
    Marriage <- clean_age(Marriage, Marriage$BRIDE_AGE)
    Marriage <- clean_age(Marriage, Marriage$BRIDE_FTHR_AGE)
    Marriage <- clean_age(Marriage, Marriage$BRIDE_MTHR_AGE)
    #run functions on Death certificates
    Death <- clean_age_death(Death, Death$PR_AGE)
    Death <- clean_age(Death, Death$PR_FTHR_AGE)
    Death <- clean_age(Death, Death$PR_MTHR_AGE)
    
  #save output
    fwrite(Birth,
           "openarch_birth.csv.gz", sep=";", row.names=F, na="")
    fwrite(Marriage,
           "openarch_marriage.csv.gz", sep=";", row.names=F, na="")
    fwrite(Death,
           "C:\\Users\\Ruben\\Documents\\02. Werk\\Clariah\\openarch\\openarch_deaths_amco_ages.csv.gz", sep=";", row.names=F, na="")
    
